/**
 * named audit-action-string-per-domain, same pattern as
 * PRESCRIPTION_AUDIT_ACTIONS ( 17) / RETURN_AUDIT_ACTIONS ( 16).
 */
export const COUPON_AUDIT_ACTIONS = {
  COUPON_CREATED: 'COUPON_CREATED',
  COUPON_UPDATED: 'COUPON_UPDATED',
  COUPON_ACTIVATED: 'COUPON_ACTIVATED',
  COUPON_DEACTIVATED: 'COUPON_DEACTIVATED',
  COUPON_ARCHIVED: 'COUPON_ARCHIVED',
  COUPON_APPLIED: 'COUPON_APPLIED',
  COUPON_REMOVED: 'COUPON_REMOVED',
  COUPON_USAGE_COMMITTED: 'COUPON_USAGE_COMMITTED',
  COUPON_USAGE_RELEASED: 'COUPON_USAGE_RELEASED',
  COUPON_CONFIG_CHANGED: 'COUPON_CONFIG_CHANGED',
  COUPON_FEATURE_ENABLED: 'COUPON_FEATURE_ENABLED',
  COUPON_FEATURE_DISABLED: 'COUPON_FEATURE_DISABLED',
} as const;
export type CouponAuditAction = (typeof COUPON_AUDIT_ACTIONS)[keyof typeof COUPON_AUDIT_ACTIONS];
