/**
 * customer self-service account audit actions, same
 * named-audit-action-string-per-domain pattern as every other domain
 * (PRESCRIPTION_AUDIT_ACTIONS, RETURN_AUDIT_ACTIONS, COUPON_AUDIT_ACTIONS, ...).
 */
export const CUSTOMER_AUDIT_ACTIONS = {
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PHONE_CHANGE_REQUESTED: 'PHONE_CHANGE_REQUESTED',
  PHONE_CHANGED: 'PHONE_CHANGED',
  ADDRESS_CREATED: 'ADDRESS_CREATED',
  ADDRESS_UPDATED: 'ADDRESS_UPDATED',
  ADDRESS_DELETED: 'ADDRESS_DELETED',
  DEFAULT_ADDRESS_CHANGED: 'DEFAULT_ADDRESS_CHANGED',
  ACCOUNT_DEACTIVATED: 'ACCOUNT_DEACTIVATED',
   // address-scoped mobile-OTP verification (address-verification.service.ts).
  ADDRESS_MOBILE_VERIFIED: 'ADDRESS_MOBILE_VERIFIED',
} as const;
export type CustomerAuditAction = (typeof CUSTOMER_AUDIT_ACTIONS)[keyof typeof CUSTOMER_AUDIT_ACTIONS];
